/*
 * Copyright (c) IT Support BD https://itsupport.com.bd. All rights reserved.
 * This file is part of AMPOS.
 *
 * This program is not free software: you can not redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License...
 * (Commercial licenses available at https://ampos.itsupport.com.bd/pricing)
 */

/**
 * vfsService.ts
 *
 * Virtual File System (VFS) for AmPOS Terminal.
 * Stores filesystem entries in localStorage under 'ampos_vfs' with pre-populated
 * system files (/etc/hosts, /etc/resolv.conf, /etc/os-release, etc.).
 */

import { getSetupConfig, getEffectiveNetwork, AMPOS_VERSION } from './setupConfigService';

// ─── Types ────────────────────────────────────────────────────────────────────

export type VFSEntryType = 'dir' | 'file';

export interface VFSEntry {
  path: string; // Absolute path, e.g. "/etc/hosts"
  type: VFSEntryType;
  content?: string;
  updatedAt?: number;
}

const VFS_LS_KEY = 'ampos_vfs';

// ─── Pre-populated Default VFS ────────────────────────────────────────────────

export function buildDefaultVFS(): Record<string, VFSEntry> {
  const cfg = getSetupConfig();
  const net = getEffectiveNetwork(cfg);
  const user = cfg.adminUsername || 'admin';
  const home = `/home/${user}`;

  const entries: VFSEntry[] = [
    { path: '/', type: 'dir' },
    { path: '/home', type: 'dir' },
    { path: home, type: 'dir' },
    { path: `${home}/Documents`, type: 'dir' },
    { path: `${home}/Downloads`, type: 'dir' },
    { path: `${home}/logs`, type: 'dir' },
    {
      path: `${home}/welcome.txt`,
      type: 'file',
      content: `Welcome to AmPOS Linux ${AMPOS_VERSION}!\nType 'help' for available commands.\n`,
    },
    { path: '/etc', type: 'dir' },
    {
      path: '/etc/hosts',
      type: 'file',
      content: `127.0.0.1   localhost\n127.0.1.1   ${cfg.hostname}\n${net.ip}    ${cfg.hostname} ${cfg.hostname}.local\n::1         localhost ip6-localhost ip6-loopback\n`,
    },
    {
      path: '/etc/resolv.conf',
      type: 'file',
      content: `# Generated by AmPOS NetworkManager\nnameserver ${cfg.dns1 || '8.8.8.8'}\nnameserver ${cfg.dns2 || '8.8.4.4'}\nsearch localdomain\n`,
    },
    {
      path: '/etc/os-release',
      type: 'file',
      content: `NAME="AmPOS Linux"\nVERSION="${AMPOS_VERSION} (Stable)"\nID=ampos\nPRETTY_NAME="AmPOS Linux ${AMPOS_VERSION} (GNU/Linux 6.6.21-amd64)"\n`,
    },
    { path: '/var', type: 'dir' },
    { path: '/var/log', type: 'dir' },
    {
      path: '/var/log/syslog',
      type: 'file',
      content: `systemd[1]: Started AmPOS Server Shell.\nsystemd[1]: Reached target Multi-User System.\n`,
    },
    { path: '/tmp', type: 'dir' },
  ];

  const map: Record<string, VFSEntry> = {};
  entries.forEach((e) => {
    map[e.path] = { ...e, updatedAt: Date.now() };
  });
  return map;
}

// ─── Storage Operations ──────────────────────────────────────────────────────

export function getVFS(): Record<string, VFSEntry> {
  try {
    const raw = localStorage.getItem(VFS_LS_KEY);
    if (!raw) {
      const initial = buildDefaultVFS();
      saveVFS(initial);
      return initial;
    }
    return JSON.parse(raw);
  } catch {
    return buildDefaultVFS();
  }
}

export function saveVFS(vfs: Record<string, VFSEntry>): void {
  try {
    localStorage.setItem(VFS_LS_KEY, JSON.stringify(vfs));
  } catch {
    // Best effort
  }
}

// ─── Path Resolution ──────────────────────────────────────────────────────────

/**
 * Normalizes absolute or relative paths:
 *  - Handles ~ => /home/<user>
 *  - Handles . and ..
 *  - Strips trailing slashes (except root "/")
 */
export function normalizePath(target: string, cwd: string, username = 'admin'): string {
  const home = `/home/${username}`;
  let p = target.trim();

  if (!p) return cwd;

  if (p === '~' || p.startsWith('~/')) {
    p = p.replace(/^~/, home);
  }

  if (!p.startsWith('/')) {
    p = `${cwd === '/' ? '' : cwd}/${p}`;
  }

  const parts = p.split('/').filter(Boolean);
  const stack: string[] = [];

  for (const part of parts) {
    if (part === '.') continue;
    if (part === '..') {
      stack.pop();
    } else {
      stack.push(part);
    }
  }

  return '/' + stack.join('/');
}

// ─── VFS Operations ───────────────────────────────────────────────────────────

export function getEntry(path: string): VFSEntry | null {
  const vfs = getVFS();
  return vfs[path] || null;
}

export function listDirectory(dirPath: string): { name: string; isDir: boolean }[] {
  const vfs = getVFS();
  const normalized = dirPath === '/' ? '/' : dirPath.replace(/\/$/, '');
  const entry = vfs[normalized];

  if (!entry || entry.type !== 'dir') return [];

  const prefix = normalized === '/' ? '/' : `${normalized}/`;
  const result: { name: string; isDir: boolean }[] = [];

  Object.keys(vfs).forEach((p) => {
    if (p === normalized || !p.startsWith(prefix)) return;
    const rel = p.slice(prefix.length);
    // Only direct children (no additional slashes)
    if (rel && !rel.includes('/')) {
      result.push({
        name: rel,
        isDir: vfs[p].type === 'dir',
      });
    }
  });

  return result.sort((a, b) => (a.isDir === b.isDir ? a.name.localeCompare(b.name) : a.isDir ? -1 : 1));
}

export function makeDirectory(path: string): boolean {
  const vfs = getVFS();
  if (vfs[path]) return false; // already exists

  // Ensure parent directory exists
  const parent = path.substring(0, path.lastIndexOf('/')) || '/';
  if (!vfs[parent] || vfs[parent].type !== 'dir') {
    makeDirectory(parent);
  }

  vfs[path] = { path, type: 'dir', updatedAt: Date.now() };
  saveVFS(vfs);
  return true;
}

export function createFile(path: string, content = ''): boolean {
  const vfs = getVFS();
  const parent = path.substring(0, path.lastIndexOf('/')) || '/';

  // Ensure parent exists
  if (!vfs[parent]) {
    makeDirectory(parent);
  }

  vfs[path] = { path, type: 'file', content, updatedAt: Date.now() };
  saveVFS(vfs);
  return true;
}

export function readFile(path: string): string | null {
  const entry = getEntry(path);
  if (!entry || entry.type !== 'file') return null;
  return entry.content ?? '';
}

export function writeFile(path: string, content: string, append = false): boolean {
  const vfs = getVFS();
  const entry = vfs[path];
  const finalContent = append && entry?.content ? entry.content + content : content;
  return createFile(path, finalContent);
}
